version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lazyapp_backend
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    networks:
      - lazyapp_network

  # Service pour le développement avec hot reload
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: lazyapp_backend_dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - lazyapp_network
    profiles:
      - dev

networks:
  lazyapp_network:
    driver: bridge
